using FluentAssertions;
using FreestyleCombo.AI.Services;
using FreestyleCombo.API.Features.Auth;
using FreestyleCombo.API.Features.Auth.ExternalSignIn;
using FreestyleCombo.Core.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using FreestyleCombo.Infrastructure.Data;
using Microsoft.Extensions.Configuration;
using Moq;

namespace FreestyleCombo.Tests.Features;

public class ExternalSignInHandlerTests
{
    private static Mock<UserManager<AppUser>> CreateUserManagerMock()
    {
        return new Mock<UserManager<AppUser>>(
            Mock.Of<IUserStore<AppUser>>(),
            null!, null!, null!, null!, null!, null!, null!, null!);
    }

    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new AppDbContext(options);
    }

    private static ITokenService CreateTokenService() => new TokenService(
        new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["JwtSettings:Secret"] = "super-secret-key-with-at-least-32-chars",
                ["JwtSettings:Issuer"] = "FreestyleComboAPI",
                ["JwtSettings:Audience"] = "FreestyleComboApp"
            })
            .Build());

    [Fact]
    public async Task NewUser_CreatesAccountWithAutoGeneratedUsername()
    {
        await using var db = CreateDb();
        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);
        userManager.Setup(m => m.FindByEmailAsync("newperson@example.com")).ReturnsAsync((AppUser?)null);
        userManager.Setup(m => m.FindByNameAsync("newperson")).ReturnsAsync((AppUser?)null);
        AppUser? created = null;
        userManager.Setup(m => m.CreateAsync(It.IsAny<AppUser>()))
            .Callback<AppUser>(u => created = u)
            .ReturnsAsync(IdentityResult.Success);
        userManager.Setup(m => m.GetRolesAsync(It.IsAny<AppUser>())).ReturnsAsync([]);

        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("google", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("sub-123", "newperson@example.com", "New Person"));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        var result = await handler.Handle(new ExternalSignInCommand("google", "tok"), CancellationToken.None);

        result.Token.Should().NotBeNullOrWhiteSpace();
        created.Should().NotBeNull();
        created!.UserName.Should().Be("newperson");
        created.Email.Should().Be("newperson@example.com");
        created.AuthProvider.Should().Be("google");
        created.ExternalSubject.Should().Be("sub-123");
        created.EmailConfirmed.Should().BeTrue();
    }

    [Fact]
    public async Task NewUser_UsernameCollision_AppendsSuffix()
    {
        await using var db = CreateDb();
        db.Users.Add(new AppUser { Id = Guid.NewGuid(), UserName = "newperson", Email = "existing@example.com" });
        await db.SaveChangesAsync();

        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);
        userManager.Setup(m => m.FindByEmailAsync("newperson@example.com")).ReturnsAsync((AppUser?)null);
        userManager.Setup(m => m.FindByNameAsync("newperson")).ReturnsAsync(db.Users.First());
        userManager.Setup(m => m.FindByNameAsync("newperson2")).ReturnsAsync((AppUser?)null);
        AppUser? created = null;
        userManager.Setup(m => m.CreateAsync(It.IsAny<AppUser>()))
            .Callback<AppUser>(u => created = u)
            .ReturnsAsync(IdentityResult.Success);
        userManager.Setup(m => m.GetRolesAsync(It.IsAny<AppUser>())).ReturnsAsync([]);

        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("google", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("sub-456", "newperson@example.com", null));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        await handler.Handle(new ExternalSignInCommand("google", "tok"), CancellationToken.None);

        created!.UserName.Should().Be("newperson2");
    }

    [Fact]
    public async Task ReturningUser_MatchesBySubject()
    {
        await using var db = CreateDb();
        var existing = new AppUser { Id = Guid.NewGuid(), UserName = "rafael", Email = "rafael@example.com", AuthProvider = "google", ExternalSubject = "sub-789" };
        db.Users.Add(existing);
        await db.SaveChangesAsync();

        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);
        userManager.Setup(m => m.GetRolesAsync(existing)).ReturnsAsync([]);

        var verifier = new Mock<IIdTokenVerifier>();
        // No email on this token — matches how Google/Apple omit it after the first grant.
        verifier.Setup(v => v.VerifyAsync("google", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("sub-789", null, null));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        var result = await handler.Handle(new ExternalSignInCommand("google", "tok"), CancellationToken.None);

        result.UserId.Should().Be(existing.Id);
        userManager.Verify(m => m.CreateAsync(It.IsAny<AppUser>()), Times.Never);
    }

    [Fact]
    public async Task ExistingPasswordAccount_AutoLinksByEmail()
    {
        await using var db = CreateDb();
        var existing = new AppUser { Id = Guid.NewGuid(), UserName = "rafael", Email = "rafael@example.com" };
        db.Users.Add(existing);
        await db.SaveChangesAsync();

        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);
        userManager.Setup(m => m.FindByEmailAsync("rafael@example.com")).ReturnsAsync(existing);
        userManager.Setup(m => m.UpdateAsync(existing))
            .Callback<AppUser>(u => { existing.AuthProvider = u.AuthProvider; existing.ExternalSubject = u.ExternalSubject; })
            .ReturnsAsync(IdentityResult.Success);
        userManager.Setup(m => m.GetRolesAsync(existing)).ReturnsAsync([]);

        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("apple", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("apple-sub-1", "rafael@example.com", null));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        var result = await handler.Handle(new ExternalSignInCommand("apple", "tok"), CancellationToken.None);

        result.UserId.Should().Be(existing.Id);
        existing.AuthProvider.Should().Be("apple");
        existing.ExternalSubject.Should().Be("apple-sub-1");
        userManager.Verify(m => m.CreateAsync(It.IsAny<AppUser>()), Times.Never);
    }

    [Fact]
    public async Task ExistingLinkedAccount_DifferentProviderSameEmail_OverwritesProviderAndSubject()
    {
        await using var db = CreateDb();
        var existing = new AppUser
        {
            Id = Guid.NewGuid(),
            UserName = "rafael",
            Email = "rafael@example.com",
            AuthProvider = "google",
            ExternalSubject = "old-google-sub"
        };
        db.Users.Add(existing);
        await db.SaveChangesAsync();

        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);
        userManager.Setup(m => m.FindByEmailAsync("rafael@example.com")).ReturnsAsync(existing);
        userManager.Setup(m => m.UpdateAsync(existing))
            .Callback<AppUser>(u => { existing.AuthProvider = u.AuthProvider; existing.ExternalSubject = u.ExternalSubject; })
            .ReturnsAsync(IdentityResult.Success);
        userManager.Setup(m => m.GetRolesAsync(existing)).ReturnsAsync([]);

        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("apple", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("apple-sub-2", "rafael@example.com", null));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        var result = await handler.Handle(new ExternalSignInCommand("apple", "tok"), CancellationToken.None);

        result.UserId.Should().Be(existing.Id);
        existing.AuthProvider.Should().Be("apple");
        existing.ExternalSubject.Should().Be("apple-sub-2");
        userManager.Verify(m => m.CreateAsync(It.IsAny<AppUser>()), Times.Never);
    }

    [Fact]
    public async Task InvalidToken_ThrowsUnauthorizedAccessException()
    {
        var userManager = CreateUserManagerMock();
        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("google", "bad-tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync((ExternalIdentity?)null);

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        Func<Task> act = () => handler.Handle(new ExternalSignInCommand("google", "bad-tok"), CancellationToken.None);

        await act.Should().ThrowAsync<UnauthorizedAccessException>();
    }

    [Fact]
    public async Task NoMatchAndNoEmail_ThrowsUnauthorizedAccessException()
    {
        await using var db = CreateDb();
        var userManager = CreateUserManagerMock();
        userManager.SetupGet(m => m.Users).Returns(db.Users);

        var verifier = new Mock<IIdTokenVerifier>();
        verifier.Setup(v => v.VerifyAsync("apple", "tok", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExternalIdentity("sub-no-email", null, null));

        var handler = new ExternalSignInHandler(userManager.Object, verifier.Object, CreateTokenService());
        Func<Task> act = () => handler.Handle(new ExternalSignInCommand("apple", "tok"), CancellationToken.None);

        await act.Should().ThrowAsync<UnauthorizedAccessException>();
    }
}
